project/project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
   path('admin/', admin.site.urls),
   path('pages/', include('django.contrib.flatpages.urls')),
   # path('accounts/', include('django.contrib.auth.urls')),
   path("accounts/", include("allauth.urls")),
   path('products/', include('simpleapp.urls')),
   path('news/', include('simpleapp.urlsNew')),

   #path('multiply/', include('simpleapp.view.multiply')),
]

project/simpleapp/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse

# Товар для нашей витрины
class Product(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,  # названия товаров не должны повторяться
    )
    description = models.TextField()
    quantity = models.IntegerField(
        validators=[MinValueValidator(0)],
    )
    # поле категории будет ссылаться на модель категории
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='products',  # все продукты в категории будут доступны через поле products
    )
    price = models.FloatField(
        validators=[MinValueValidator(0.0)],
    )

    def __str__(self):
        return f'{self.name.title()}: {self.description[:20]}'

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])

# Категория, к которой будет привязываться товар
class Category(models.Model):
    # названия категорий тоже не должны повторяться
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name.title()


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = int(0)
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat*3 + cRat
        self.save()

class CategoryN(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories')

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья')
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(CategoryN, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)
    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'

    def __str__(self):
        return self.preview()

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(CategoryN, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

project/templates/article_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Статья</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

project/templates/category_list.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% block title %}
Products
{% endblock title %}

{% block content %}
   <h1>Новости</h1>
    <h2>Колличество новостей :{{posts|length}}</h2>
{% if is_not_subscriber %}
<p class="text-center"><a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Подписаться</a></p>

{% endif %}
   <hr>
   {% if posts %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Статья</td>
           </tr>{{ post.title|censor }}</td>
               <td>{{ post.dateCreation|date:' d M Y' }}</td>

           {% for post in category_news_list %}
         <li class="list-group-item">
           <small class="fw-bold">{{ post.dateCreation|date:' d M Y' }}</small>
           <td>{{ post.title|censor }}</td>
           <small class="text-muted">(автор: {{ post.author}})</small><br>
           <small class="fw-bold">категории:
           {% for category in post.category.all %}
           {{category}}
               <a href="{% usrl 'category_list' category.id%}">{{category}}</a>
                {% endfor %}
           </small>
         <td>{{ post.text|truncatewords:20|censor }}</td>
         </li>
         {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}
   {# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

project/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуй! Новые статьи за последнюю неделю!</h2>
<ul>
  {% for post in posts %}
  <li><a href="{{link}}{{ post.get_absolute_url}}">{{post.title}}</a></li>
  {% endfor %}
</ul>
</body>
</html>

project/templates/new_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

project/templates/post.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
<!-- Название у нас будет Product -->
{% block title %}
Post
{% endblock title %}

{% block content %}
   <h1>{{ post.title|censor }}</h1>
    <h3>{{ post.dateCreation|date:' d M Y' }}</h3>
    <h5>{{ post.text|censor }}</h5>
{% endblock content %}

project/templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуй! Новая <a href="{{link}}">статья </a>в твоем любимом разделе</h2>
<p>{{text}}</p>
</body>
</html>

project/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление поста</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

project/templates/posts.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% block title %}
Products
{% endblock title %}

{% block content %}
   <h1>Новости</h1>
    <h2>Колличество новостей :{{posts|length}}</h2>
   <hr>
   {% if posts %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Статья</td>
           </tr>
           {% for post in posts %}
           <tr>

               <td>{{ post.title|censor }}</td>
               <td>{{ post.dateCreation|date:' d M Y' }}</td>
               <td>{{ post.text|truncatewords:20|censor }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}
   {# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

project/templates/product.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

<!-- Название у нас будет Product -->
{% block title %}
Product
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ product }}</h1>
{% endblock content %}

project/templates/product_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

project/templates/product_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

project/templates/products.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Products
{% endblock title %}

{% block content %}
    <h1>Все товары</h1>

    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="Найти" />
    </form>

    <hr>

    {# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}
    {% if perms.simpleapp.add_product %}
    <a href="{% url 'product_create' %}">Добавить товар</a>
    {% endif %}

    {% if products %}
        <table>
            <tr>
                <td>Название</td>
                <td>Описание</td>
                <td>Категория</td>
                <td>Цена</td>
                <td>Количество</td>

                {# Условие получается составным. #}
                {% if perms.simpleapp.change_product or perms.simpleapp.delete_product %}
                <td>Действия</td>
                {% endif %}

            </tr>

            {% for product in products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.description|truncatechars:15 }}</td>
                <td>{{ product.category.name }}</td>
                <td>{{ product.price|currency }}</td>
                <td>{{ product.quantity }}</td>

                <td>
                    {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
                    {% if perms.simpleapp.change_product %}
                    <a href="{% url 'product_update' pk=product.id %}">Изменить</a>
                    {% endif %}
                    {% if perms.simpleapp.delete_product %}
                    <a href="{% url 'product_delete' product.id %}">Удалить</a>
                    {% endif %}
                </td>

            </tr>
            {% endfor %}

        </table>
    {% else %}
        <h2>Товаров нет!</h2>
    {% endif %}

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

project/templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Posts
{% endblock title %}
{% block content %}
    <h1>Список новостей ({{ news|length }})</h1>
    <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
    </form>
    <hr>
    {% if search %}
        <table style="margin-left: auto; margin-right: auto;">
            <tr>
                <td>Заголовок</td>
                <td>Категории</td>
                <td>Дата публикации</td>
            </tr>
            {% for new in search %}
            <tr>
                <td>{{ new.title|censor }}</td>
                <td>{{ new.category_type }}</td>
                <td>{{ new.dateCreation|date:'d M Y H:i' }}</td>
            </tr>
            {% endfor %}

        </table>
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}
<!-- {# Добавляем пагинацию на страницу #}-->

<!--   {# Информация о предыдущих страницах #}-->
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

<!--   {# Информация о текущей странице #}-->
   {{ page_obj.number }}

<!--   {# Информация о следующих страницах #}-->
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

project/templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1> class="text-center"{{message}} {{category}}</h1>
{% endblock content %}